name: Testing

on: [push, pull_request]

jobs:
  test:
    name: Test on .NET Core #for ${{ matrix.os }}
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use .NET 3.1.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Building
        run: |
          dotnet build MathCore/MathCore.csproj          
          dotnet build Tests/MathCore.Tests/MathCore.Tests.csproj

      - name: Run Tests
        run: dotnet test Tests/MathCore.Tests/MathCore.Tests.csproj
